spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wealthwisedb
      #my local db dont have pass so kept emty
      #username :
      #password :
  application:
    name: wealthwise
