spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wealthy
    username: root
    password: Radhika653
    driver-class-name: com.mysql.cj.jdbc.Driver
    default.schema: wealthy

# Hibernate (JPA) Properties
  jpa.database-platform: org.hibernate.dialect.MySQLDialect
  jpa.hibernate.ddl-auto: Update
  jpa.show-sql: true
  jpa.generate-ddl: true
  jpa.properties.hibernate.format_sql: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
logging.level.org.hibernate.SQL: DEBUG