# spring:
#   datasource:
#     url: jdbc:mysql://127.0.0.1:3306/wealthy
#     username: root
#     password: Radhika653
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     default.schema: wealthy
#   liquibase:
#     enabled: true
#     change-log: classpath:master-liquibase-changelog.xml

# # Hibernate (JPA) Properties
#   jpa:
#     database-platform: org.hibernate.dialect.MySQLDialect
#     show-sql: true
#     generate-ddl: true
#     properties:
#       hibernate:
#         ddl-auto: Update
#         format_sql: true
#         dialect: org.hibernate.dialect.MySQL5Dialect
  
# logging.level.org.hibernate.SQL: DEBUG